### ISSUE TITLE
Tickets don't register purchase id currently

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedTickets#29]
When a ticket is bought, we don't save the transaction id

**Comment by halvors** [comment]
Is this still a problem? This should reallt be fixed.

**Comment by petterroea** [comment]
@halvors Can you finish it? I wrote some stuff to pass payment id, but it is still not working. I think the fault lies at paymenthandler.php line 40 -  i think i am fetching the ID of the item we inserted wrong. Can you have a look?

**Comment by halvors** [comment]
@petterroea This works just fine, all the entries in the payments table contains transactionId. What doesn't work is that the paymentId in tickets table never is set.

**Comment by petterroea** [comment]
Yeah, that's the issue
